Test: Create missing switch branches for on taxonomy changed
Error: "'switch' statement on enum type
'org.wordpress.android.fluxc.action.TaxonomyAction' misses cases:
'FETCH_TERM', 'PUSH_TERM', 'DELETE_TERM', 'FETCHED_TERMS',
'FETCHED_TERM', 'PUSHED_TERM', 'DELETED_TERM' and 'REMOVE_ALL_TERMS'"